### ISSUE TITLE
Call Graph seems blocked. Java project too big?

### ISSUE THREAD

**Issue by jkleiser** [Chentai-Kao/call-graph-plugin-public#6]
I just wanted to try Call Graph on our rather big Java 8 project. When I specify the Directory and hit Run, Call Graph finds 5421 functions, but then seems to get stuck. I see that this exception has been caught:
```
java.lang.NoClassDefFoundError: guru/nidi/graphviz/model/Factory
	at callgraph.Utils.getLayoutFromGraphViz(Utils.kt:276)
	at callgraph.Utils.layout(Utils.kt:108)
	at callgraph.CanvasBuilder.buildGraph(CanvasBuilder.kt:39)
	at callgraph.CanvasBuilder.build(CanvasBuilder.kt:27)
	at callgraph.CallGraphToolWindow$run$1.run(CallGraphToolWindow.kt:217)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:945)
	at callgraph.Utils$runBackgroundTask$1.run(Utils.kt:124)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: guru.nidi.graphviz.model.Factory PluginClassLoader[call-graph, 0.1.12] 
<img width="684" alt="Call Graph" src="https://user-images.githubusercontent.com/107986/59094946-9ba44d00-8917-11e9-85c8-838339ef77a4.png">
<img width="684" alt="Call Graph" src="https://user-images.githubusercontent.com/107986/59094997-b676c180-8917-11e9-9b77-022ef5af198e.png">

com.intellij.ide.plugins.cl.PluginClassLoader@608b4af8
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:51)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more
```

What may be the reason for this?

**Comment by jkleiser** [comment]
<img width="684" alt="Call Graph" src="https://user-images.githubusercontent.com/107986/59095091-f047c800-8917-11e9-996a-ec6232a3b934.png">

**Comment by nabarunnag** [comment]
I am experiencing the same problem
